### ISSUE TITLE
"A file can't load itself" error when loading from .carp/libs/

### ISSUE THREAD

**Issue by spencerking** [carpentry-org/file#2]
I am new to carp and am seeing the following error when trying to load the library:
```
A file can't load itself: 'file.carp' at /Users/spencerking/.carp/libs/github.com_COLON_carpentry-org/file/0.0.4/file.carp:1:7.
```

Please correct me if I am wrong, but it appears the library is expected to have a main.carp file and file.carp would then need to define a File module.

I would be happy to assist with fixing this issue, assuming it is an actual issue and not a mistake on my part.

Edit:
I should probably note, I was unable to get the library to load automatically from git so I cloned it manually.

**Comment by hellerve** [comment]
I’m sorry to hear you’re having trouble getting my library to work!

I’m unable to reproduce that error when using `(load "git@github.com:carpentry-org/file@0.0.4")` on my machine. 

There are two places where Carp looks for an entry point in a library, either in `main.carp` or in `<packagename>.carp`, which means that `file.carp` for `file` is actually correct. Could you please verify that the clone was successful and the files are unchanged compared to either `master` or `0.0.4`. In neither form should `file.carp` import itself.

Side note: it seems as if `0.0.4` is broken on Carp’s current `master`, though, while the current master branch works.

**Comment by hellerve** [comment]
I just pushed `0.0.5`, which should work on the newest version of Carp (once we figure out how to get it to run on your machine, that is)!

**Comment by spencerking** [comment]
Thanks for the responses. I've got it working now. I must have accidentally moved file.carp from tests up to the top directory when moving my cloned copy into ~/.carp

**Comment by hellerve** [comment]
Glad to hear it worked! Have fun with the library!
